services:
  - type: web
    name: aqi-predictor-app
    env: docker
    region: oregon
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 8501
      - key: ENVIRONMENT
        value: production
    healthCheckPath: /_stcore/health
    autoDeploy: true